apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep1
  template:
    metadata:
      labels:
        app: dep1
    spec:
      containers:
        - name: dep1
          image: march30acr.azurecr.io/march10repo
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dep1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: dep1
